// Deliberately bounded sample replies: these are not generated by an LLM.
export function demoReply(message, context = '') {
 const text = message.toLowerCase().trim();
 if(context && /i’d like to explore|i'd like to explore/.test(text))
   return 'Let’s use the '+context+' example as a starting point, not a conclusion. A useful first step is to understand the decision your team makes today, the information available and what a better outcome would be worth. Which part most closely matches your situation? This preview can frame the conversation; it cannot yet analyse your business.';
 if (/^(hi|hey|hello|good morning|good afternoon)\b/.test(text) || /how are you/.test(text))
   return 'Hello—good to meet you. I’m here to help you explore what ROI AI could bring to your business. This is a guided demo for now. What brought you here today?';
 if (/cost|price|pricing|budget|fee/.test(text))
   return 'There isn’t a published price I can quote. The scope depends on the decision, the systems involved and the support your team needs. A useful starting point is the cost of leaving the problem unsolved. What is taking the most time or holding back progress?';
 if (/drone|agri|farm|crop|food|geospatial/.test(text) && !/export|trade|customs|international/.test(text))
   return 'Agrifood & AgriTech is our first focus. Potential starting points include drone and geospatial insight, precision operations and visibility across the supply chain. The useful question is which decision better information would change. Are you looking at field operations or the wider business?';
 if (/export|trade|customs|international/.test(text))
   return 'For export and trade, we would start with where information or repeated work slows a decision: market intelligence, compliance workflows or commercial priorities. Human review remains important for regulatory decisions. Where is the friction today?';
 if (/finance|invest|diligence|capital/.test(text))
   return 'For investment teams, the focus is better evidence: diligence, portfolio visibility and the business case for technology. AI can help organise information; it should not replace accountable judgment. Are you evaluating an opportunity, or improving an existing business?';
 if (/sell|sales|customer|grow|commercial/.test(text))
   return 'A useful starting point is understanding where customer insight is being lost between the market and your team. That can reveal opportunities in propositions, priorities or sales enablement. Which part of the customer journey would you most like to improve?';
 if (/operation|supply|inventory|automat|workflow/.test(text))
   return 'Start with one recurring workflow. Map who does it, what information they need and where time is lost. That gives a basis for deciding whether the answer is automation, better visibility or simply a clearer process. Which workflow comes to mind?';
 if (/how.*work|approach|start|help|sector/.test(text))
   return 'We begin with the business problem, identify where value could be created, then choose the right response—build, buy, integrate or do nothing. Adoption and measurement are part of that plan from day one. What would a better outcome look like for your team?';
 if (/thank/.test(text)) return 'You’re welcome. You can explore the capabilities and sectors on the site, or bring another question here when you’re ready.';
 return 'This preview uses a small set of guided answers, so I can’t yet reason about every detail of your situation. The live advisor will need its AI connection and verified knowledge base. For now, we can explore our approach, sectors, automation, growth or investment decisions.';
}
