// Deliberately bounded sample replies: these are not generated by an LLM.
export function demoReply(message, context = '') {
 const text = message.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
 if(context && /i’d like to explore|i'd like to explore|vorrei esplorare|je voudrais explorer|me gustaria explorar|gostaria de explorar/.test(text))
   return "Tomemos el ejemplo "+context+" como punto de partida, no como conclusión. Un primer paso útil es comprender qué decide tu equipo hoy, qué información tiene y qué valor tendría un resultado mejor. ¿Qué parte se parece más a tu situación? Esta vista previa puede orientar la conversación, pero aún no analizar tu negocio.";
 if (/^(hi|hey|hello|good morning|good afternoon|ciao|salve|buongiorno|bonjour|salut|bonsoir|hola|buenos dias|buenas tardes|ola|oi|bom dia|boa tarde)\b/.test(text) || /how are you|come stai|comment allez|como estas|como vai/.test(text))
   return "Hola, un gusto conocerte. Estoy aquí para ayudarte a explorar lo que ROI AI podría aportar a tu negocio. Por ahora es una demostración guiada. ¿Qué te ha traído hoy?";
 if (/cost|price|pricing|budget|fee|prezz|prix|tarif|precio|preco|orcamento/.test(text))
   return "No hay un precio publicado que pueda darte. El alcance depende de la decisión, los sistemas implicados y el apoyo que necesite tu equipo. Un punto de partida útil es el coste de dejar el problema sin resolver. ¿Qué consume más tiempo o frena el avance?";
 if (/drone|agri|farm|crop|food|geospatial|agro|campo|lavoura|geospaz|geoespa/.test(text) && !/export|trade|customs|international|esport|dogan|douan|aduan|alfand|internaz|commercio|commerce|comercio/.test(text))
   return "La agroalimentación y AgriTech son nuestro primer foco. Podemos empezar por datos de drones y geoespaciales, operaciones de precisión o visibilidad de la cadena de suministro. La pregunta útil es qué decisión cambiaría con mejor información. ¿Te interesan las operaciones de campo o el negocio en general?";
 if (/export|trade|customs|international|esport|dogan|douan|aduan|alfand|internaz|commercio|commerce|comercio/.test(text))
   return "En exportación y comercio empezaríamos donde la información o el trabajo repetido ralentizan una decisión: inteligencia de mercado, cumplimiento o prioridades comerciales. La revisión humana sigue siendo importante en las decisiones normativas. ¿Dónde encuentras hoy la fricción?";
 if (/financ|finanz|invest|invers|diligence|capital/.test(text))
   return "Para los equipos de inversión, el foco está en mejores evidencias: due diligence, visibilidad de cartera y justificación de la tecnología. La IA puede organizar información, pero no debe sustituir el criterio responsable. ¿Estás evaluando una oportunidad o mejorando un negocio existente?";
 if (/sell|sales|customer|grow|commercial|comercial|client|vend|cresc|croiss|crecim/.test(text))
   return "Un punto de partida útil es entender dónde se pierde conocimiento del cliente entre el mercado y tu equipo. Eso puede revelar oportunidades en propuestas, prioridades o apoyo a ventas. ¿Qué parte del recorrido del cliente te gustaría mejorar más?";
 if (/operation|operaz|operac|supply|inventory|automat|workflow|logist|supriment|suministr|approvision|flusso/.test(text))
   return "Empieza por un flujo de trabajo recurrente. Identifica quién lo realiza, qué información necesita y dónde se pierde tiempo. Así podrás decidir si hace falta automatización, más visibilidad o simplemente un proceso más claro. ¿Qué flujo te viene a la mente?";
 if (/how.*work|approach|start|help|sector|come.*lavor|comment.*travaill|como.*trab|como.*trabalh|approccio|approche|enfoque|abordagem|settore|secteur|setor|aiut|aide|ayud|ajud/.test(text))
   return "Partimos del problema del negocio, identificamos dónde crear valor y elegimos la respuesta adecuada: construir, comprar, integrar o no hacer nada. La adopción y la medición forman parte del plan desde el primer día. ¿Cómo sería un resultado mejor para tu equipo?";
 if (/thank|grazie|merci|gracias|obrigad/.test(text)) return "De nada. Puedes explorar las capacidades y los sectores del sitio o volver con otra pregunta cuando quieras.";
 return "Esta vista previa usa un conjunto limitado de respuestas guiadas, así que aún no puedo razonar sobre todos los detalles de tu situación. El asesor en directo necesitará una conexión de IA y una base de conocimiento verificada. Por ahora podemos explorar el enfoque, los sectores, la automatización, el crecimiento o la inversión.";
}
