// Deliberately bounded sample replies: these are not generated by an LLM.
export function demoReply(message, context = '') {
 const text = message.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
 if(context && /i’d like to explore|i'd like to explore|vorrei esplorare|je voudrais explorer|me gustaria explorar|gostaria de explorar/.test(text))
   return "Usiamo l’esempio "+context+" come punto di partenza, non come conclusione. Un primo passo utile è capire la decisione che il tuo team prende oggi, le informazioni disponibili e il valore di un risultato migliore. Quale parte rispecchia di più la tua situazione? Questa anteprima può orientare la conversazione, ma non può ancora analizzare la tua impresa.";
 if (/^(hi|hey|hello|good morning|good afternoon|ciao|salve|buongiorno|bonjour|salut|bonsoir|hola|buenos dias|buenas tardes|ola|oi|bom dia|boa tarde)\b/.test(text) || /how are you|come stai|comment allez|como estas|como vai/.test(text))
   return "Ciao, piacere di conoscerti. Sono qui per aiutarti a esplorare ciò che Heading South potrebbe portare alla tua impresa. Per ora è una demo guidata. Cosa ti ha portato qui oggi?";
 if (/cost|price|pricing|budget|fee|prezz|prix|tarif|precio|preco|orcamento/.test(text))
   return "Non c’è un prezzo pubblicato che possa indicarti. Il perimetro dipende dalla decisione, dai sistemi coinvolti e dal supporto necessario al team. Un punto di partenza utile è il costo di lasciare il problema irrisolto. Cosa assorbe più tempo o frena i progressi?";
 if (/drone|agri|farm|crop|food|geospatial|agro|campo|lavoura|geospaz|geoespa/.test(text) && !/export|trade|customs|international|esport|dogan|douan|aduan|alfand|internaz|commercio|commerce|comercio/.test(text))
   return "Agroalimentare e AgriTech sono il nostro primo focus. I punti di partenza possono includere dati da droni e geospaziali, operazioni di precisione e visibilità sulla filiera. La domanda utile è quale decisione cambierebbe con informazioni migliori. Ti interessano le attività sul campo o l’impresa nel suo insieme?";
 if (/export|trade|customs|international|esport|dogan|douan|aduan|alfand|internaz|commercio|commerce|comercio/.test(text))
   return "Per export e commercio partiremo da dove informazioni o attività ripetute rallentano una decisione: intelligence di mercato, conformità o priorità commerciali. La revisione umana resta importante nelle decisioni normative. Dove trovi oggi gli attriti?";
 if (/financ|finanz|invest|invers|diligence|capital/.test(text))
   return "Per i team d’investimento, il focus sono evidenze migliori: due diligence, visibilità di portafoglio e valore della tecnologia. L’AI può organizzare le informazioni, ma non deve sostituire il giudizio responsabile. Stai valutando un’opportunità o migliorando un’impresa esistente?";
 if (/sell|sales|customer|grow|commercial|comercial|client|vend|cresc|croiss|crecim/.test(text))
   return "Un punto di partenza utile è capire dove la conoscenza dei clienti si perde tra il mercato e il team. Può rivelare opportunità nelle proposte, nelle priorità o nel supporto alle vendite. Quale parte del percorso del cliente vorresti migliorare di più?";
 if (/operation|operaz|operac|supply|inventory|automat|workflow|logist|supriment|suministr|approvision|flusso/.test(text))
   return "Parti da un flusso di lavoro ricorrente. Mappa chi lo svolge, le informazioni necessarie e dove si perde tempo. Avrai una base per decidere se servono automazione, più visibilità o semplicemente un processo più chiaro. Quale flusso ti viene in mente?";
 if (/how.*work|approach|start|help|sector|come.*lavor|comment.*travaill|como.*trab|como.*trabalh|approccio|approche|enfoque|abordagem|settore|secteur|setor|aiut|aide|ayud|ajud/.test(text))
   return "Partiamo dal problema aziendale, individuiamo dove creare valore e scegliamo la risposta giusta: costruire, acquistare, integrare oppure non intervenire. Adozione e misurazione fanno parte del piano fin dal primo giorno. Come sarebbe un risultato migliore per il tuo team?";
 if (/thank|grazie|merci|gracias|obrigad/.test(text)) return "Prego. Puoi esplorare competenze e settori sul sito o tornare qui con un’altra domanda quando vuoi.";
 return "Questa anteprima usa un numero limitato di risposte guidate, quindi non posso ancora ragionare su ogni dettaglio della tua situazione. Il consulente live richiederà la connessione AI e una base di conoscenza verificata. Per ora possiamo esplorare approccio, settori, automazione, crescita o investimenti.";
}
