// Deliberately bounded sample replies: these are not generated by an LLM.
export function demoReply(message, context = '') {
 const text = message.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
 if(context && /i’d like to explore|i'd like to explore|vorrei esplorare|je voudrais explorer|me gustaria explorar|gostaria de explorar/.test(text))
   return "Vamos usar o exemplo "+context+" como ponto de partida, não como conclusão. Um primeiro passo útil é entender a decisão que sua equipe toma hoje, as informações disponíveis e o valor de um resultado melhor. Qual parte mais se parece com sua situação? Esta prévia pode orientar a conversa, mas ainda não analisar seu negócio.";
 if (/^(hi|hey|hello|good morning|good afternoon|ciao|salve|buongiorno|bonjour|salut|bonsoir|hola|buenos dias|buenas tardes|ola|oi|bom dia|boa tarde)\b/.test(text) || /how are you|come stai|comment allez|como estas|como vai/.test(text))
   return "Olá, prazer em conhecer você. Estou aqui para ajudar a explorar o que a ROI AI pode trazer ao seu negócio. Por enquanto, esta é uma demonstração guiada. O que trouxe você aqui hoje?";
 if (/cost|price|pricing|budget|fee|prezz|prix|tarif|precio|preco|orcamento/.test(text))
   return "Não há um preço publicado que eu possa informar. O escopo depende da decisão, dos sistemas envolvidos e do apoio necessário à equipe. Um bom ponto de partida é o custo de deixar o problema sem solução. O que consome mais tempo ou impede o avanço?";
 if (/drone|agri|farm|crop|food|geospatial|agro|campo|lavoura|geospaz|geoespa/.test(text) && !/export|trade|customs|international|esport|dogan|douan|aduan|alfand|internaz|commercio|commerce|comercio/.test(text))
   return "Agroalimentação e AgriTech são nosso foco inicial. Podemos começar por dados de drones e geoespaciais, operações de precisão ou visibilidade da cadeia de suprimentos. A pergunta útil é qual decisão mudaria com informações melhores. Você está pensando nas operações de campo ou no negócio como um todo?";
 if (/export|trade|customs|international|esport|dogan|douan|aduan|alfand|internaz|commercio|commerce|comercio/.test(text))
   return "Em exportação e comércio, começaríamos onde informações ou tarefas repetidas atrasam uma decisão: inteligência de mercado, conformidade ou prioridades comerciais. A revisão humana continua importante nas decisões regulatórias. Onde estão os atritos hoje?";
 if (/financ|finanz|invest|invers|diligence|capital/.test(text))
   return "Para equipes de investimento, o foco são evidências melhores: due diligence, visibilidade do portfólio e justificativa da tecnologia. A IA pode organizar informações, mas não deve substituir o julgamento responsável. Você está avaliando uma oportunidade ou melhorando um negócio existente?";
 if (/sell|sales|customer|grow|commercial|comercial|client|vend|cresc|croiss|crecim/.test(text))
   return "Um bom ponto de partida é entender onde o conhecimento do cliente se perde entre o mercado e sua equipe. Isso pode revelar oportunidades em propostas, prioridades ou apoio às vendas. Qual parte da jornada do cliente você mais gostaria de melhorar?";
 if (/operation|operaz|operac|supply|inventory|automat|workflow|logist|supriment|suministr|approvision|flusso/.test(text))
   return "Comece por um fluxo de trabalho recorrente. Identifique quem o realiza, quais informações são necessárias e onde se perde tempo. Isso ajuda a decidir se a resposta é automação, mais visibilidade ou simplesmente um processo mais claro. Qual fluxo vem à sua mente?";
 if (/how.*work|approach|start|help|sector|come.*lavor|comment.*travaill|como.*trab|como.*trabalh|approccio|approche|enfoque|abordagem|settore|secteur|setor|aiut|aide|ayud|ajud/.test(text))
   return "Partimos do problema do negócio, identificamos onde criar valor e escolhemos a resposta certa: construir, comprar, integrar ou não fazer nada. Adoção e medição fazem parte do plano desde o primeiro dia. Como seria um resultado melhor para sua equipe?";
 if (/thank|grazie|merci|gracias|obrigad/.test(text)) return "De nada. Você pode explorar as competências e os setores do site ou voltar com outra pergunta quando quiser.";
 return "Esta prévia usa um conjunto limitado de respostas guiadas, então ainda não posso analisar todos os detalhes da sua situação. O consultor ao vivo precisará de uma conexão de IA e de uma base de conhecimento verificada. Por enquanto, podemos explorar a abordagem, os setores, a automação, o crescimento ou os investimentos.";
}
