const content = {
  agritech:{eyebrow:'Sector / First focus',title:'Intelligence that reaches the ground.',lede:'Agrifood is where real-world complexity, scarce resources and consequential decisions meet.',opportunityTitle:'From field to supply chain, make every decision carry further.',opportunityCopy:'Better data only matters when it improves what people can see, decide and do. We connect physical operations with intelligence that makes a measurable difference.',image:'assets/agritech-aerial.png',focus:[['01','Precision operations','Focus attention, inputs and effort where they can have the greatest impact.'],['02','Drone & geospatial intelligence','Turn aerial and field data into a clearer, more timely view of what is happening.'],['03','Supply-chain insight','Make complexity visible across production, inventory and the movement of goods.']]},
  trade:{eyebrow:'Sector / Export & trade',title:'Clarity across every crossing.',lede:'Trade depends on timely, confident decisions in an environment that rarely stands still.',opportunityTitle:'Turn external complexity into internal advantage.',opportunityCopy:'We help teams see the information that matters, reduce the drag around repeat decisions and move with more conviction.',image:'assets/trade-port.png',focus:[['01','Market intelligence','Bring signals from markets, customers and operations into clearer view.'],['02','Compliance workflows','Reduce friction around the controls and processes that keep trade moving.'],['03','Commercial decisions','Equip teams to act earlier and with a more complete picture.']]},
  investing:{eyebrow:'Sector / Finance & investment',title:'Conviction, with better evidence.',lede:'Better investment decisions begin with a clearer view of the opportunity—and the work required to realise it.',opportunityTitle:'Make diligence and judgment work together.',opportunityCopy:'ROI AI helps investment teams focus intelligence on the questions that determine where capital and attention can create lasting value.',image:'assets/investment-table.png',focus:[['01','Due diligence','Find the questions beneath the obvious before the decision is made.'],['02','Portfolio intelligence','Create a better shared view of performance, risk and opportunity.'],['03','Investment decisions','Connect technology choices to the case for value creation.']]},
  operations:{eyebrow:'Sector / Operations',title:'Make complex work flow.',lede:'The most valuable innovation is often found in the everyday work that holds an organisation together.',opportunityTitle:'Less friction. Better visibility. Stronger performance.',opportunityCopy:'We help operational teams focus technology on the points where people, process and information are working harder than they need to.',image:'assets/trade-port.png',focus:[['01','Forecasting','Replace hindsight with a more useful view of what is coming.'],['02','Workflow redesign','Shape work around the decisions people need to make, not legacy process.'],['03','Performance visibility','Give leaders a clearer view of what moves the operation forward.']]},
  commercial:{eyebrow:'Sector / Growth',title:'Turn insight into momentum.',lede:'Growth comes from seeing a customer, market or opportunity more clearly than the competition.',opportunityTitle:'Make every route to growth more intelligent.',opportunityCopy:'We work with commercial teams to turn customer understanding into propositions, priorities and better decisions in market.',image:'assets/investment-table.png',focus:[['01','Customer insight','Find the patterns that reveal what customers need next.'],['02','Proposition design','Turn intelligence into offers people can understand and choose.'],['03','Sales enablement','Give teams more useful context at the moment it matters.']]},
  operate:{eyebrow:'Capability / Operate smarter',title:'Make the work work better.',lede:'Technology should remove friction, sharpen decisions and give good people more room to do their best work.',opportunityTitle:'Focus intelligence on the work that moves the organisation.',opportunityCopy:'We find practical improvements in the operating model, then help turn them into a reality teams will actually adopt.',image:'assets/trade-port.png',focus:[['01','Decision design','Clarify the moments where a better decision can create disproportionate value.'],['02','Automation','Remove repetitive effort without losing the judgment that makes work human.'],['03','Adoption','Build change into the work from the beginning, not after launch.']]},
  grow:{eyebrow:'Capability / Grow further',title:'Make growth more knowable.',lede:'The best growth decisions combine commercial instinct with a more complete understanding of the market.',opportunityTitle:'Find momentum—and give it somewhere to go.',opportunityCopy:'We help leaders turn data and signals into customer insight, stronger propositions and a clearer route forward.',image:'assets/agritech-aerial.png',focus:[['01','Customer understanding','Bring fragmented signals together around the people you serve.'],['02','New propositions','Test where technology can unlock a more valuable offer.'],['03','Commercial focus','Direct effort toward the opportunities most likely to compound.']]},
  invest:{eyebrow:'Capability / Invest better',title:'Put ambition where it can compound.',lede:'The right technology decision is not always to build. The important thing is knowing why.',opportunityTitle:'Make the technology decision a value decision.',opportunityCopy:'We bring structure to the choices around investment, vendors and implementation—so each decision earns its place in the business.',image:'assets/investment-table.png',focus:[['01','Opportunity assessment','Start with the value that could be created, not the technology on offer.'],['02','Build / buy / integrate','Choose the response that fits the opportunity—not a predetermined answer.'],['03','Return design','Set out how value will be measured before money and momentum are committed.']]}
};
const topic = new URLSearchParams(location.search).get('topic') || 'agritech';
const page = content[topic] || content.agritech;
document.title = `ROI AI — ${page.eyebrow.split('/').pop().trim()}`;
document.querySelector('#eyebrow').textContent = page.eyebrow;
document.querySelector('#title').textContent = page.title;
document.querySelector('#lede').textContent = page.lede;
document.querySelector('#opportunityTitle').textContent = page.opportunityTitle;
document.querySelector('#opportunityCopy').textContent = page.opportunityCopy;
document.querySelector('#hero').style.backgroundImage = `url('${page.image}')`;
document.querySelector('#index').textContent = `${String(Object.keys(content).indexOf(topic) + 1).padStart(2,'0')} / ROI AI`;
document.querySelector('#focusGrid').innerHTML = page.focus.map(([number,title,copy]) => `<article><span>${number}</span><h3>${title}</h3><p>${copy}</p></article>`).join('');
