// Editorial demonstrations, not client data, live analysis or model-generated advice.
export const sectors = ['agritech','trade','investing','operations','commercial'];
export const experiences = {
 agritech:{name:"Agroalimentación y AgriTech",kind:'field',image:'agritech-aerial',label:"Inteligencia sobre el terreno.",question:"¿Dónde conviene centrar ahora la atención?",inputs:"Observaciones de campo · Imágenes aéreas · Contexto operativo",scenarios:[
  {label:"Asignación de recursos",point:"Variabilidad en el campo",observe:"En este ejemplo, una zona presenta un aspecto distinto al cultivo circundante.",interpret:"Una imagen puede plantear una pregunta, pero no determinar por sí sola la causa.",act:"Contrasta la señal aérea con observaciones sobre el terreno antes de cambiar un insumo o una intervención.",measure:"Sigue el problema verificado, la acción realizada y el uso de recursos frente a una referencia comparable."},
  {label:"Inspección anticipada",point:"Prioridad de inspección",observe:"Un estudio de ejemplo destaca una zona que merece un examen más detenido.",interpret:"El valor está en orientar el tiempo limitado de inspección, no en tratar cada señal como un diagnóstico.",act:"Proporciona al equipo de campo una lista de inspecciones priorizadas con las imágenes de referencia y las incertidumbres.",measure:"Compara el tiempo de verificación, los problemas no detectados y las inspecciones innecesarias."},
  {label:"Visibilidad del suministro",point:"Del campo al plan",observe:"En el ejemplo, las previsiones de producción han cambiado, pero el plan de suministro no.",interpret:"Una señal útil debe llegar a quienes asumen compromisos en las etapas posteriores.",act:"Conecta una actualización de producción verificada al proceso de planificación, con un responsable de decisión identificado.",measure:"Revisa la precisión de la planificación, las correcciones y la rapidez de la respuesta acordada."}
 ]},
 trade:{name:"Exportación y comercio",kind:'route',image:'trade-port',label:"Claridad más allá de las fronteras.",question:"¿Qué oportunidad merece el siguiente paso?",inputs:"Señales de mercado · Preparación comercial · Limitaciones de acceso",scenarios:[
  {label:"Entrada en el mercado",point:"Señal de mercado",observe:"Un mercado ficticio muestra interés de clientes, pero la forma de atenderlo no se ha probado.",interpret:"La demanda es solo una parte de la decisión. La entrega, el margen y la preparación local aún necesitan evidencias.",act:"Prepara un informe que separe la demanda confirmada de las hipótesis y las limitaciones sin resolver.",measure:"Sigue el coste y la rapidez de validación de la oportunidad antes de comprometerte con la expansión."},
  {label:"Flujo comercial",point:"Traspaso de documentos",observe:"En este ejemplo, varios equipos introducen la misma información del envío.",interpret:"La gestión repetida puede difuminar responsabilidades y generar trabajo evitable.",act:"Mapea los traspasos y prueba una fuente de información compartida, manteniendo la revisión especializada para las decisiones de cumplimiento.",measure:"Compara los tiempos de gestión, las correcciones y las excepciones antes y después de un piloto controlado."},
  {label:"Prioridades comerciales",point:"Acceso al cliente",observe:"Varias consultas de exportación compiten por la atención del mismo equipo.",interpret:"El pedido aparentemente más grande no es necesariamente la mejor oportunidad.",act:"Compara preparación, adecuación al cliente e hipótesis de entrega en un único informe de decisión compartido.",measure:"Evalúa el esfuerzo de calificación y el avance según los criterios acordados por el equipo comercial."}
 ]},
 investing:{name:"Finanzas e inversión",kind:'evidence',image:'investment-table',label:"La evidencia antes de la convicción.",question:"¿Qué cambiaría tu decisión?",inputs:"Fuentes · Hipótesis de valor · Criterios de decisión",scenarios:[
  {label:"Análisis exhaustivo",point:"Falta de evidencia",observe:"Un caso de inversión de ejemplo depende de una mejora operativa que no se ha verificado.",interpret:"Una narrativa convincente no equivale a una palanca de valor demostrada.",act:"Rastrea la hipótesis hasta las fuentes y asigna al equipo de due diligence una pregunta que resolver.",measure:"Sigue qué hipótesis relevantes se verifican, se cuestionan o quedan sin resolver antes de decidir."},
  {label:"Visión de cartera",point:"Perspectiva compartida",observe:"En este ejemplo, las actualizaciones de cartera describen el rendimiento de formas distintas.",interpret:"Comparar es difícil cuando difieren las definiciones, los periodos y las responsabilidades.",act:"Acuerda una estructura común de evidencias y destaca las excepciones sin perder el contexto de gestión.",measure:"Evalúa el esfuerzo de elaboración de informes, la comparabilidad y el tiempo dedicado a resolver preguntas relevantes."},
  {label:"Caso tecnológico",point:"Palanca de valor",observe:"La propuesta de ejemplo promete automatización, pero omite la adopción y los costes operativos.",interpret:"La decisión necesita una visión de todo el ciclo de vida, no una afirmación aislada de eficiencia.",act:"Construye un caso transparente con costes, dependencias, hipótesis de adopción y una condición de parada.",measure:"Compara el valor realizado con las hipótesis iniciales y el coste total de propiedad."}
 ]},
 operations:{name:"Operaciones y cadenas de suministro",kind:'flow',image:'trade-port',label:"Menos fricción. Más fluidez.",question:"¿Dónde pierde impulso el trabajo?",inputs:"Eventos del proceso · Traspasos entre equipos · Historial de excepciones",scenarios:[
  {label:"Traspasos",point:"Punto de espera",observe:"Un pedido ilustrativo espera un traspaso manual entre dos equipos.",interpret:"El cuello de botella puede ser una responsabilidad poco clara, no una herramienta que falta.",act:"Mapea la decisión y prueba un traspaso más claro antes de introducir automatización.",measure:"Compara los tiempos, las correcciones y el número de excepciones sin resolver."},
  {label:"Previsión",point:"Señal de planificación",observe:"En este ejemplo, la planificación usa una visión antigua de la demanda mientras las nuevas señales están en otro lugar.",interpret:"Un dato más reciente solo es útil si puede cambiar una decisión de planificación con responsabilidad clara.",act:"Integra las señales relevantes en un proceso de planificación revisado y contrástalas con la referencia existente.",measure:"Evalúa el error de previsión, el esfuerzo de planificación y las consecuencias de las decisiones modificadas."},
  {label:"Excepciones",point:"Criterio humano",observe:"La mayoría de los pedidos de ejemplo siguen un camino previsible; algunos requieren criterio experto.",interpret:"Tratar todos los casos igual hace perder tiempo u oculta los inusuales.",act:"Separa la gestión rutinaria de una cola explícita de excepciones bajo responsabilidad humana.",measure:"Sigue las finalizaciones sin intervención manual junto con las tasas de error y las excepciones sin resolver."}
 ]},
 commercial:{name:"Crecimiento y desarrollo comercial",kind:'flow',image:'investment-table',label:"Comprender. Después actuar.",question:"¿Qué te están diciendo tus clientes?",inputs:"Conversaciones con clientes · Señales comerciales · Conocimiento del equipo",scenarios:[
  {label:"Conocimiento del cliente",point:"Señal ignorada",observe:"Una inquietud recurrente de clientes aparece en varias conversaciones de ejemplo.",interpret:"Un tema recurrente es una hipótesis inicial, no una prueba de una necesidad de todo el mercado.",act:"Reúne las conversaciones originales y valida el tema con el grupo de clientes adecuado.",measure:"Comprueba si el conocimiento validado cambia una propuesta, una decisión o un resultado para el cliente."},
  {label:"Contexto de ventas",point:"Momento relevante",observe:"Un equipo de cuentas de ejemplo no puede ver fácilmente lo que un cliente ya ha comentado.",interpret:"La oportunidad es una conversación mejor informada, no simplemente más contactos.",act:"Muestra el contexto relevante de la cuenta con los permisos adecuados y deja que el equipo decida cómo responder.",measure:"Evalúa el esfuerzo de preparación, la utilidad para el equipo y la calidad de las conversaciones resultantes."},
  {label:"Nueva propuesta",point:"Hipótesis de valor",observe:"Un posible servicio aborda un problema del cliente, pero se desconoce la disposición a adoptarlo.",interpret:"Construir ahora la oferta completa comprometería recursos antes de probar la hipótesis central.",act:"Crea una prueba acotada de la propuesta con evidencias claras necesarias para continuar.",measure:"Revisa el interés demostrado, las barreras de adopción y la decisión de desarrollar, adaptar o detenerse."}
 ]},
 operate:{name:"Operar mejor",kind:'flow',image:'trade-port',label:"Diseña el trabajo en torno a la decisión.",question:"¿Qué debe fluir y qué requiere criterio?",inputs:"Conocimiento del proceso · Muestras de trabajo · Responsabilidad de decisión",scenarios:[
  {label:"Reducir fricciones",point:"Esfuerzo repetido",observe:"Un flujo de ejemplo transfiere la misma información a través de tres traspasos.",interpret:"Automatizar el proceso actual podría mantener su complejidad innecesaria.",act:"Elimina pasos redundantes, aclara responsabilidades y prueba la automatización útil más sencilla.",measure:"Sigue los tiempos y las correcciones, junto con la experiencia de quienes hacen el trabajo."},
  {label:"Apoyar el criterio",point:"Momento de decisión",observe:"Una decisión recurrente de ejemplo requiere información repartida entre varias fuentes.",interpret:"La intervención útil puede ser un informe de decisión más claro, no un agente autónomo.",act:"Aporta al responsable evidencias vinculadas a las fuentes y conserva una etapa explícita de revisión.",measure:"Revisa el tiempo de preparación, la calidad de las evidencias y la coherencia de las decisiones."}
 ]},
 grow:{name:"Crecer más",kind:'route',image:'agritech-aerial',label:"Dale una dirección a la oportunidad.",question:"¿Qué hipótesis de crecimiento deberías probar primero?",inputs:"Evidencias de clientes · Contexto de mercado · Hipótesis de la propuesta",scenarios:[
  {label:"Identificar la necesidad",point:"Problema del cliente",observe:"Un grupo de clientes de ejemplo utiliza una solución provisional para un problema recurrente.",interpret:"La solución provisional puede revelar una necesidad no cubierta, pero su alcance y urgencia siguen siendo inciertos.",act:"Valida el problema con ese grupo antes de comprometerte con un nuevo producto o servicio.",measure:"Revisa las evidencias de la necesidad, las barreras de adopción y la disposición al cambio."},
  {label:"Elegir un camino",point:"Camino de crecimiento",observe:"Dos caminos de crecimiento de ejemplo compiten por los mismos recursos.",interpret:"Elegir exige hipótesis explícitas sobre adecuación, esfuerzo y tiempo de aprendizaje.",act:"Diseña una prueba acotada para cada camino y compara las evidencias según criterios de decisión compartidos.",measure:"Sigue el coste del aprendizaje y las evidencias que respaldan continuar, adaptar o detenerse."}
 ]},
 invest:{name:"Invertir mejor",kind:'evidence',image:'investment-table',label:"Cada compromiso necesita una razón.",question:"¿Construir, comprar, integrar o esperar?",inputs:"Necesidad del negocio · Limitaciones de los sistemas · Valor durante todo el ciclo de vida",scenarios:[
  {label:"Elegir la respuesta",point:"Criterios de decisión",observe:"Un equipo de ejemplo quiere un nuevo sistema de IA, pero parte de sus necesidades podría estar ya cubierta.",interpret:"La nueva tecnología es solo una de las posibles respuestas al problema del negocio.",act:"Compara las capacidades existentes, una solución comercial y un desarrollo a medida con los mismos requisitos.",measure:"Evalúa la adopción, el coste total, la facilidad de mantenimiento y las evidencias de valor, no la novedad de la herramienta."},
  {label:"Diseñar el retorno",point:"Hipótesis de valor",observe:"Una propuesta enumera beneficios sin explicar cuándo ni cómo se medirán.",interpret:"Una promesa sin medir es difícil de gestionar y fácil de exagerar.",act:"Acuerda una referencia, un responsable del valor, puntos de revisión y condiciones explícitas para detenerse o cambiar de rumbo.",measure:"Compara el valor realizado y los costes con el caso acordado, incluido lo que no mejoró."}
 ]}
};
export function getScenario(key,index=0){const item=experiences[key];return item?.scenarios[index]||item?.scenarios[0];}
