// Editorial demonstrations, not client data, live analysis or model-generated advice.
export const sectors = ['agritech','trade','investing','operations','commercial'];
export const experiences = {
 agritech:{name:"Agroalimentação e AgriTech",kind:'field',image:'agritech-aerial',label:"Inteligência no campo.",question:"Onde concentrar a atenção agora?",inputs:"Observações de campo · Imagens aéreas · Contexto operacional",scenarios:[
  {label:"Foco nos recursos",point:"Variação no campo",observe:"Neste exemplo, uma área apresenta um aspecto diferente do restante da lavoura.",interpret:"Uma imagem pode levantar uma questão, mas não determinar a causa por si só.",act:"Compare o sinal aéreo com observações de campo antes de alterar um insumo ou uma intervenção.",measure:"Acompanhe o problema verificado, a ação realizada e o uso de recursos em relação a uma linha de base comparável."},
  {label:"Inspeção antecipada",point:"Prioridade de inspeção",observe:"Um levantamento de exemplo destaca uma área que merece uma análise mais próxima.",interpret:"O valor está em direcionar o tempo limitado de inspeção, não em tratar cada sinal como um diagnóstico.",act:"Forneça à equipe de campo uma lista de inspeções priorizadas, com as imagens de referência e as incertezas.",measure:"Compare o tempo de verificação, os problemas não detectados e as inspeções desnecessárias."},
  {label:"Visibilidade do abastecimento",point:"Do campo ao plano",observe:"No exemplo, a previsão de produção mudou, mas o plano de abastecimento não.",interpret:"Um sinal útil deve chegar a quem assume compromissos nas etapas seguintes.",act:"Conecte uma atualização de produção verificada ao processo de planejamento, com um responsável pela decisão identificado.",measure:"Avalie a precisão do planejamento, o retrabalho e a rapidez da resposta acordada."}
 ]},
 trade:{name:"Exportação e comércio",kind:'route',image:'trade-port',label:"Clareza além das fronteiras.",question:"Qual oportunidade merece o próximo passo?",inputs:"Sinais de mercado · Preparo comercial · Restrições de acesso",scenarios:[
  {label:"Entrada no mercado",point:"Sinal de mercado",observe:"Um mercado fictício mostra interesse de clientes, mas a forma de atendê-lo ainda não foi testada.",interpret:"A demanda é apenas parte da decisão. Entrega, margem e preparo local ainda precisam de evidências.",act:"Prepare um documento que separe a demanda confirmada das hipóteses e restrições não resolvidas.",measure:"Acompanhe o custo e a rapidez de validação da oportunidade antes de investir na expansão."},
  {label:"Fluxo comercial",point:"Transferência de documentos",observe:"Neste exemplo, várias equipes inserem as mesmas informações da remessa.",interpret:"O tratamento repetido pode tornar responsabilidades pouco claras e gerar trabalho evitável.",act:"Mapeie as passagens e teste uma fonte compartilhada de informações, mantendo a revisão especializada nas decisões de conformidade.",measure:"Compare o tempo de processamento, as correções e as exceções antes e depois de um piloto controlado."},
  {label:"Prioridades comerciais",point:"Caminho até o cliente",observe:"Várias consultas de exportação disputam a atenção da mesma equipe.",interpret:"O pedido aparentemente maior não é necessariamente a melhor oportunidade.",act:"Compare preparo, adequação ao cliente e hipóteses de entrega em um único documento de decisão compartilhado.",measure:"Avalie o esforço de qualificação e o avanço conforme os critérios acordados pela equipe comercial."}
 ]},
 investing:{name:"Finanças e investimentos",kind:'evidence',image:'investment-table',label:"As evidências antes da convicção.",question:"O que mudaria sua decisão?",inputs:"Fontes · Hipóteses de valor · Critérios de decisão",scenarios:[
  {label:"Análise aprofundada",point:"Lacuna nas evidências",observe:"Um caso de investimento de exemplo depende de uma melhoria operacional ainda não verificada.",interpret:"Uma narrativa convincente não equivale a um fator de geração de valor comprovado.",act:"Rastreie a hipótese até as fontes e atribua à equipe de due diligence uma pergunta a resolver.",measure:"Acompanhe quais hipóteses relevantes são verificadas, questionadas ou ficam sem resposta antes da decisão."},
  {label:"Visão do portfólio",point:"Perspectiva compartilhada",observe:"Neste exemplo, as atualizações do portfólio descrevem o desempenho de formas diferentes.",interpret:"A comparação é difícil quando definições, períodos e responsabilidades diferem.",act:"Defina uma estrutura comum de evidências e destaque as exceções sem perder o contexto da gestão.",measure:"Avalie o esforço de elaboração de relatórios, a comparabilidade e o tempo dedicado a resolver questões relevantes."},
  {label:"Caso tecnológico",point:"Fator de geração de valor",observe:"A proposta de exemplo promete automação, mas omite adoção e custos operacionais.",interpret:"A decisão exige uma visão de todo o ciclo de vida, não uma alegação isolada de eficiência.",act:"Construa um caso transparente com custos, dependências, hipóteses de adoção e uma condição de parada.",measure:"Compare o valor realizado com as hipóteses iniciais e o custo total de propriedade."}
 ]},
 operations:{name:"Operações e cadeias de suprimentos",kind:'flow',image:'trade-port',label:"Menos atrito. Mais fluidez.",question:"Onde o trabalho perde impulso?",inputs:"Eventos do processo · Passagens entre equipes · Histórico de exceções",scenarios:[
  {label:"Passagens de trabalho",point:"Ponto de espera",observe:"Um pedido ilustrativo aguarda uma passagem manual entre duas equipes.",interpret:"O gargalo pode ser uma responsabilidade pouco clara, não a falta de uma ferramenta.",act:"Mapeie a decisão e teste uma passagem mais clara antes de introduzir automação.",measure:"Compare prazos, retrabalho e número de exceções não resolvidas."},
  {label:"Previsão",point:"Sinal de planejamento",observe:"Neste exemplo, o planejamento usa uma visão antiga da demanda enquanto novos sinais estão em outro lugar.",interpret:"Um dado mais recente só é útil se puder mudar uma decisão de planejamento com responsabilidade clara.",act:"Integre os sinais relevantes a um processo de planejamento revisado e teste-os em relação à linha de base existente.",measure:"Avalie o erro de previsão, o esforço dos planejadores e as consequências das decisões alteradas."},
  {label:"Exceções",point:"Julgamento humano",observe:"A maioria dos pedidos de exemplo segue um caminho previsível; alguns exigem julgamento experiente.",interpret:"Tratar todos os casos da mesma forma desperdiça tempo ou esconde os incomuns.",act:"Separe o processamento de rotina de uma fila explícita de exceções sob responsabilidade humana.",measure:"Acompanhe as conclusões sem intervenção manual junto com as taxas de erro e as exceções não resolvidas."}
 ]},
 commercial:{name:"Crescimento e desenvolvimento comercial",kind:'flow',image:'investment-table',label:"Compreender. Depois agir.",question:"O que seus clientes estão dizendo?",inputs:"Conversas com clientes · Sinais comerciais · Conhecimento da equipe",scenarios:[
  {label:"Conhecimento do cliente",point:"Sinal ignorado",observe:"Uma preocupação recorrente de clientes aparece em várias conversas de exemplo.",interpret:"Um tema recorrente é uma hipótese inicial, não uma prova de necessidade de todo o mercado.",act:"Reúna as conversas originais e valide o tema com o grupo de clientes adequado.",measure:"Verifique se o conhecimento validado muda uma proposta, uma decisão ou um resultado para o cliente."},
  {label:"Contexto de vendas",point:"Momento relevante",observe:"Uma equipe de contas de exemplo não consegue ver facilmente o que um cliente já discutiu.",interpret:"A oportunidade é uma conversa mais bem informada, não simplesmente mais contatos.",act:"Apresente o contexto relevante da conta com as permissões adequadas e deixe a equipe decidir como responder.",measure:"Avalie o esforço de preparação, a utilidade para a equipe e a qualidade das conversas resultantes."},
  {label:"Nova proposta",point:"Hipótese de valor",observe:"Um possível serviço atende a um problema do cliente, mas a disposição para adotá-lo é desconhecida.",interpret:"Construir a oferta completa agora comprometeria recursos antes de testar a hipótese central.",act:"Crie um teste limitado da proposta, com evidências claras necessárias para continuar.",measure:"Avalie o interesse demonstrado, as barreiras à adoção e a decisão de desenvolver, adaptar ou parar."}
 ]},
 operate:{name:"Operar melhor",kind:'flow',image:'trade-port',label:"Organize o trabalho em torno da decisão.",question:"O que deve fluir e o que exige julgamento?",inputs:"Conhecimento dos processos · Amostras de trabalho · Responsabilidade pelas decisões",scenarios:[
  {label:"Reduzir atritos",point:"Esforço repetido",observe:"Um fluxo de exemplo transfere as mesmas informações em três passagens de trabalho.",interpret:"Automatizar o processo atual pode preservar sua complexidade desnecessária.",act:"Elimine etapas redundantes, esclareça responsabilidades e teste a automação útil mais simples.",measure:"Acompanhe prazos e retrabalho, junto com a experiência de quem realiza o trabalho."},
  {label:"Apoiar o julgamento",point:"Momento de decisão",observe:"Uma decisão recorrente de exemplo exige informações distribuídas por várias fontes.",interpret:"A intervenção útil pode ser um documento de decisão mais claro, em vez de um agente autônomo.",act:"Forneça ao responsável evidências vinculadas às fontes e mantenha uma etapa explícita de revisão.",measure:"Avalie o tempo de preparação, a qualidade das evidências e a consistência das decisões."}
 ]},
 grow:{name:"Crescer mais",kind:'route',image:'agritech-aerial',label:"Dê uma direção à oportunidade.",question:"Qual hipótese de crescimento você deve testar primeiro?",inputs:"Evidências dos clientes · Contexto de mercado · Hipóteses da proposta",scenarios:[
  {label:"Identificar a necessidade",point:"Problema do cliente",observe:"Um grupo de clientes de exemplo usa uma solução improvisada para um problema recorrente.",interpret:"A solução improvisada pode revelar uma necessidade não atendida, mas sua dimensão e urgência ainda são incertas.",act:"Valide o problema com esse grupo antes de investir em um novo produto ou serviço.",measure:"Avalie as evidências da necessidade, as barreiras à adoção e a disposição para mudar."},
  {label:"Escolher um caminho",point:"Caminho de crescimento",observe:"Dois caminhos de crescimento de exemplo disputam os mesmos recursos.",interpret:"A escolha exige hipóteses explícitas sobre adequação, esforço e tempo de aprendizado.",act:"Crie um teste limitado para cada caminho e compare as evidências segundo critérios de decisão compartilhados.",measure:"Acompanhe o custo do aprendizado e as evidências que sustentam continuar, adaptar ou parar."}
 ]},
 invest:{name:"Investir melhor",kind:'evidence',image:'investment-table',label:"Cada compromisso precisa de uma justificativa.",question:"Construir, comprar, integrar ou esperar?",inputs:"Necessidade do negócio · Restrições dos sistemas · Valor ao longo do ciclo de vida",scenarios:[
  {label:"Escolher a resposta",point:"Critérios de decisão",observe:"Uma equipe de exemplo quer um novo sistema de IA, mas parte das necessidades pode já estar atendida.",interpret:"Uma nova tecnologia é apenas uma das possíveis respostas ao problema do negócio.",act:"Compare as capacidades existentes, uma solução de mercado e um desenvolvimento sob medida com os mesmos requisitos.",measure:"Avalie adoção, custo total, facilidade de manutenção e evidências de valor, não a novidade da ferramenta."},
  {label:"Planejar o retorno",point:"Hipóteses de valor",observe:"Uma proposta lista benefícios sem explicar quando ou como serão medidos.",interpret:"Uma promessa sem medição é difícil de gerenciar e fácil de exagerar.",act:"Defina uma linha de base, um responsável pelo valor, pontos de revisão e condições explícitas para parar ou mudar de rumo.",measure:"Compare o valor realizado e os custos com o caso acordado, incluindo o que não melhorou."}
 ]}
};
export function getScenario(key,index=0){const item=experiences[key];return item?.scenarios[index]||item?.scenarios[0];}
