// Editorial demonstrations, not client data, live analysis or model-generated advice.
export const sectors = ['agritech','trade','investing','operations','commercial'];
export const experiences = {
 agritech:{name:'Agrifood & AgriTech',kind:'field',image:'agritech-aerial',label:'Intelligence, grounded.',question:'Where should attention go next?',inputs:'Field observations · Aerial imagery · Operational context',scenarios:[
  {label:'Resource focus',point:'Field variation',observe:'In this example, one area looks different from the surrounding crop.',interpret:'An image can identify a question; it cannot establish the cause on its own.',act:'Compare the aerial signal with field observations before changing an input or intervention.',measure:'Track the verified issue, the action taken and the resource use against a comparable baseline.'},
  {label:'Earlier inspection',point:'Inspection priority',observe:'An example survey highlights an area that deserves a closer look.',interpret:'The value is in directing scarce inspection time—not treating every signal as a diagnosis.',act:'Give the field team a prioritised inspection list with the underlying imagery and uncertainty.',measure:'Compare time to verification, missed issues and unnecessary inspections.'},
  {label:'Supply visibility',point:'From field to plan',observe:'The example production outlook has changed, but the supply plan has not.',interpret:'A useful signal needs to reach the people making downstream commitments.',act:'Connect a verified production update to the planning workflow, with a named decision owner.',measure:'Review planning accuracy, rework and the speed of an agreed response.'}
 ]},
 trade:{name:'Export & Trade',kind:'route',image:'trade-port',label:'Clarity across borders.',question:'Which opportunity deserves the next move?',inputs:'Market signals · Commercial readiness · Route constraints',scenarios:[
  {label:'Market entry',point:'Market signal',observe:'A fictional market shows customer interest, but the route to serving it is untested.',interpret:'Demand is one part of the decision. Delivery, margin and local readiness still need evidence.',act:'Build an evidence brief that separates confirmed demand from assumptions and unresolved constraints.',measure:'Track the cost and speed of validating the opportunity before committing to expansion.'},
  {label:'Trade workflow',point:'Document handoff',observe:'In this example, the same shipment information is entered by several teams.',interpret:'Repeated handling can obscure ownership and create avoidable work.',act:'Map the handoffs and test a shared source of information, keeping specialist review for compliance decisions.',measure:'Compare handling time, corrections and exceptions before and after a controlled pilot.'},
  {label:'Commercial focus',point:'Route to customer',observe:'Several export enquiries compete for the same team’s attention.',interpret:'The largest apparent order is not necessarily the strongest opportunity.',act:'Compare readiness, customer fit and delivery assumptions in one shared decision brief.',measure:'Review qualification effort and progression against the criteria agreed by the commercial team.'}
 ]},
 investing:{name:'Finance & Investment',kind:'evidence',image:'investment-table',label:'Evidence before conviction.',question:'What would change your decision?',inputs:'Source material · Value assumptions · Decision criteria',scenarios:[
  {label:'Diligence',point:'Evidence gap',observe:'An example investment case depends on an operational improvement that has not been verified.',interpret:'A compelling narrative is not the same as an evidenced value driver.',act:'Trace the assumption to source material and assign a question for the diligence team to resolve.',measure:'Track which material assumptions are verified, challenged or left unresolved before a decision.'},
  {label:'Portfolio view',point:'Shared perspective',observe:'In this example, portfolio updates describe performance in different ways.',interpret:'Comparison is difficult when definitions, periods and ownership differ.',act:'Agree a common evidence structure and surface exceptions without removing management context.',measure:'Review reporting effort, comparability and time spent resolving material questions.'},
  {label:'Technology case',point:'Value driver',observe:'The example proposal promises automation but omits adoption and running costs.',interpret:'The decision needs a whole-life view, not an isolated efficiency claim.',act:'Build a transparent case with costs, dependencies, adoption assumptions and a stop condition.',measure:'Compare realised value with the original assumptions and total cost of ownership.'}
 ]},
 operations:{name:'Operations & Supply Chains',kind:'flow',image:'trade-port',label:'Less friction. More flow.',question:'Where does the work lose momentum?',inputs:'Workflow events · Team handoffs · Exception history',scenarios:[
  {label:'Handoffs',point:'Waiting point',observe:'An illustrative order waits for a manual handoff between two teams.',interpret:'The bottleneck may be unclear ownership rather than a missing tool.',act:'Map the decision and test a clearer handoff before introducing automation.',measure:'Compare elapsed time, rework and the number of unresolved exceptions.'},
  {label:'Forecasting',point:'Planning signal',observe:'In this example, planning uses an old view of demand while new signals sit elsewhere.',interpret:'A more current input is useful only if it can change an accountable planning decision.',act:'Bring the relevant signals into a reviewed planning process and test them against the existing baseline.',measure:'Review forecast error, planner effort and the consequences of the changed decisions.'},
  {label:'Exceptions',point:'Human judgment',observe:'Most example orders follow a predictable path; a few need experienced judgment.',interpret:'Treating every case alike wastes time or hides the unusual ones.',act:'Separate routine handling from an explicit, human-owned exception queue.',measure:'Track straight-through completion alongside error rates and unresolved exceptions.'}
 ]},
 commercial:{name:'Growth & Commercial',kind:'flow',image:'investment-table',label:'Understand. Then move.',question:'What are your customers telling you?',inputs:'Customer conversations · Commercial signals · Team knowledge',scenarios:[
  {label:'Customer insight',point:'Unheard signal',observe:'A repeated customer concern appears in several example conversations.',interpret:'A recurring theme is a starting hypothesis, not proof of a market-wide need.',act:'Bring the source conversations together and test the theme with the right customer group.',measure:'Track whether the validated insight changes a proposition, decision or customer outcome.'},
  {label:'Sales context',point:'Moment of relevance',observe:'An example account team cannot easily see what a customer has already discussed.',interpret:'The opportunity is a more informed conversation, not simply more outreach.',act:'Surface relevant, permissioned account context and let the team decide how to respond.',measure:'Review preparation effort, usefulness to the team and quality of the resulting conversations.'},
  {label:'New proposition',point:'Value hypothesis',observe:'A possible service addresses a customer problem, but willingness to adopt is unknown.',interpret:'Building the full offer now would commit resources before the central assumption is tested.',act:'Create a small proposition test with clear evidence needed to continue.',measure:'Review demonstrated interest, adoption barriers and the decision to develop, adapt or stop.'}
 ]},
 operate:{name:'Operate smarter',kind:'flow',image:'trade-port',label:'Design the work around the decision.',question:'What should flow—and what needs judgment?',inputs:'Process knowledge · Work samples · Decision ownership',scenarios:[
  {label:'Remove friction',point:'Repeated effort',observe:'A sample workflow moves the same information across three handoffs.',interpret:'Automating the current process could preserve its unnecessary complexity.',act:'Remove redundant steps, clarify ownership and then test the smallest useful automation.',measure:'Track elapsed time and rework, alongside the experience of the people doing the work.'},
  {label:'Support judgment',point:'Decision moment',observe:'A recurring example decision requires information spread across several sources.',interpret:'The useful intervention may be a clearer decision brief rather than an autonomous agent.',act:'Bring source-linked evidence to the decision owner and retain an explicit review step.',measure:'Review preparation time, evidence quality and decision consistency.'}
 ]},
 grow:{name:'Grow further',kind:'route',image:'agritech-aerial',label:'Give opportunity a direction.',question:'Which growth assumption should you test first?',inputs:'Customer evidence · Market context · Proposition assumptions',scenarios:[
  {label:'Find the need',point:'Customer problem',observe:'An example customer group uses a workaround for a repeated problem.',interpret:'The workaround may reveal unmet value, but the size and urgency of the need remain uncertain.',act:'Test the problem with that group before committing to a new product or service.',measure:'Review evidence of the need, adoption barriers and willingness to change.'},
  {label:'Choose a route',point:'Route to growth',observe:'Two example growth routes compete for the same resources.',interpret:'Choosing requires explicit assumptions about fit, effort and time to learning.',act:'Design a bounded test for each route, then compare evidence against shared decision criteria.',measure:'Track learning cost and the evidence supporting a continue, adapt or stop decision.'}
 ]},
 invest:{name:'Invest better',kind:'evidence',image:'investment-table',label:'Every commitment has a case.',question:'Build, buy, integrate—or wait?',inputs:'Business need · System constraints · Whole-life value',scenarios:[
  {label:'Choose the response',point:'Decision criteria',observe:'An example team wants a new AI system, but part of its need may already be covered.',interpret:'New technology is only one possible response to the business problem.',act:'Compare existing capability, a purchased solution and a custom build against the same requirements.',measure:'Assess adoption, total cost, maintainability and evidence of value—not the novelty of the tool.'},
  {label:'Design the return',point:'Value assumptions',observe:'A proposal lists benefits without explaining when or how they will be measured.',interpret:'An unmeasured promise is difficult to manage and easy to overstate.',act:'Agree a baseline, a value owner, review points and explicit conditions to stop or change course.',measure:'Compare realised value and costs with the agreed case, including what did not improve.'}
 ]}
};
export function getScenario(key,index=0){const item=experiences[key];return item?.scenarios[index]||item?.scenarios[0];}
