// Editorial demonstrations, not client data, live analysis or model-generated advice.
export const sectors = ['agritech','trade','investing','operations','commercial'];
export const experiences = {
 agritech:{name:"Agroalimentare e AgriTech",kind:'field',image:'agritech-aerial',label:"Intelligence sul campo.",question:"Dove concentrare l’attenzione adesso?",inputs:"Osservazioni sul campo · Immagini aeree · Contesto operativo",scenarios:[
  {label:"Uso mirato delle risorse",point:"Variabilità in campo",observe:"In questo esempio, un’area appare diversa dalla coltura circostante.",interpret:"Un’immagine può far emergere una domanda, ma da sola non ne stabilisce la causa.",act:"Confronta il segnale aereo con le osservazioni sul campo prima di modificare un input o un intervento.",measure:"Monitora il problema verificato, l’azione intrapresa e l’uso delle risorse rispetto a una base di riferimento comparabile."},
  {label:"Ispezione anticipata",point:"Priorità di ispezione",observe:"Un rilievo di esempio evidenzia un’area che merita un esame più attento.",interpret:"Il valore sta nell’orientare il tempo limitato delle ispezioni, non nel trattare ogni segnale come una diagnosi.",act:"Fornisci al team sul campo un elenco di ispezioni prioritario con le immagini di riferimento e le incertezze.",measure:"Confronta tempi di verifica, problemi non rilevati e ispezioni non necessarie."},
  {label:"Visibilità sulla filiera",point:"Dal campo al piano",observe:"Nell’esempio, le previsioni produttive sono cambiate, ma il piano di approvvigionamento no.",interpret:"Un segnale utile deve raggiungere chi assume impegni a valle.",act:"Collega un aggiornamento produttivo verificato al processo di pianificazione, con un responsabile decisionale identificato.",measure:"Esamina precisione della pianificazione, rilavorazioni e rapidità della risposta concordata."}
 ]},
 trade:{name:"Export e commercio",kind:'route',image:'trade-port',label:"Chiarezza oltre i confini.",question:"Quale opportunità merita il prossimo passo?",inputs:"Segnali di mercato · Preparazione commerciale · Vincoli del percorso",scenarios:[
  {label:"Ingresso nel mercato",point:"Segnale di mercato",observe:"Un mercato fittizio mostra interesse da parte dei clienti, ma il modo di servirlo non è ancora verificato.",interpret:"La domanda è solo una parte della decisione. Consegna, margini e preparazione locale richiedono ancora evidenze.",act:"Prepara una sintesi che separi la domanda confermata dalle ipotesi e dai vincoli irrisolti.",measure:"Monitora costi e tempi di validazione dell’opportunità prima di impegnarti nell’espansione."},
  {label:"Flusso del commercio",point:"Passaggio documentale",observe:"In questo esempio, più team inseriscono le stesse informazioni sulla spedizione.",interpret:"I passaggi ripetuti possono rendere poco chiare le responsabilità e creare lavoro evitabile.",act:"Mappa i passaggi e testa una fonte informativa condivisa, mantenendo la revisione specialistica per le decisioni di conformità.",measure:"Confronta tempi di gestione, correzioni ed eccezioni prima e dopo un progetto pilota controllato."},
  {label:"Priorità commerciali",point:"Percorso verso il cliente",observe:"Più richieste di export competono per l’attenzione dello stesso team.",interpret:"L’ordine apparentemente più grande non è necessariamente l’opportunità migliore.",act:"Confronta preparazione, adeguatezza al cliente e ipotesi di consegna in un’unica sintesi decisionale condivisa.",measure:"Valuta lo sforzo di qualificazione e l’avanzamento rispetto ai criteri concordati dal team commerciale."}
 ]},
 investing:{name:"Finanza e investimenti",kind:'evidence',image:'investment-table',label:"Le evidenze prima della convinzione.",question:"Cosa cambierebbe la tua decisione?",inputs:"Fonti · Ipotesi di valore · Criteri decisionali",scenarios:[
  {label:"Analisi approfondita",point:"Lacuna nelle evidenze",observe:"Un caso d’investimento di esempio dipende da un miglioramento operativo non ancora verificato.",interpret:"Una narrazione convincente non equivale a una leva di valore dimostrata.",act:"Risali dall’ipotesi alle fonti e assegna al team di due diligence una domanda da risolvere.",measure:"Monitora quali ipotesi rilevanti vengono verificate, messe in discussione o lasciate irrisolte prima della decisione."},
  {label:"Visione di portafoglio",point:"Prospettiva condivisa",observe:"In questo esempio, gli aggiornamenti di portafoglio descrivono le performance in modi diversi.",interpret:"Il confronto è difficile quando definizioni, periodi e responsabilità sono diversi.",act:"Concorda una struttura comune delle evidenze e fai emergere le eccezioni senza perdere il contesto gestionale.",measure:"Valuta lo sforzo di rendicontazione, la comparabilità e il tempo dedicato a risolvere le domande rilevanti."},
  {label:"Caso tecnologico",point:"Leva di valore",observe:"La proposta di esempio promette automazione, ma omette adozione e costi operativi.",interpret:"La decisione richiede una visione dell’intero ciclo di vita, non un’affermazione isolata di efficienza.",act:"Costruisci un caso trasparente con costi, dipendenze, ipotesi di adozione e una condizione di arresto.",measure:"Confronta il valore realizzato con le ipotesi iniziali e il costo totale di possesso."}
 ]},
 operations:{name:"Operazioni e supply chain",kind:'flow',image:'trade-port',label:"Meno attriti. Più fluidità.",question:"Dove perde slancio il lavoro?",inputs:"Eventi di processo · Passaggi tra team · Storico delle eccezioni",scenarios:[
  {label:"Passaggi di consegne",point:"Punto di attesa",observe:"Un ordine illustrativo attende un passaggio manuale tra due team.",interpret:"Il collo di bottiglia potrebbe essere una responsabilità poco chiara, non uno strumento mancante.",act:"Mappa la decisione e prova un passaggio più chiaro prima di introdurre l’automazione.",measure:"Confronta tempi, rilavorazioni e numero di eccezioni irrisolte."},
  {label:"Previsioni",point:"Segnale per la pianificazione",observe:"In questo esempio, la pianificazione usa una visione superata della domanda, mentre i nuovi segnali restano altrove.",interpret:"Un dato più aggiornato è utile solo se può cambiare una decisione di pianificazione con un responsabile chiaro.",act:"Porta i segnali rilevanti in un processo di pianificazione sottoposto a revisione e testali rispetto alla base di riferimento esistente.",measure:"Valuta l’errore di previsione, lo sforzo dei pianificatori e le conseguenze delle decisioni modificate."},
  {label:"Eccezioni",point:"Giudizio umano",observe:"La maggior parte degli ordini di esempio segue un percorso prevedibile; alcuni richiedono un giudizio esperto.",interpret:"Trattare tutti i casi allo stesso modo fa perdere tempo o nasconde quelli insoliti.",act:"Separa la gestione ordinaria da una coda di eccezioni esplicita, affidata a una persona responsabile.",measure:"Monitora i completamenti senza intervento manuale insieme ai tassi di errore e alle eccezioni irrisolte."}
 ]},
 commercial:{name:"Crescita e sviluppo commerciale",kind:'flow',image:'investment-table',label:"Comprendere. Poi agire.",question:"Cosa ti stanno dicendo i clienti?",inputs:"Conversazioni con i clienti · Segnali commerciali · Conoscenza del team",scenarios:[
  {label:"Conoscenza dei clienti",point:"Segnale inascoltato",observe:"Una preoccupazione ricorrente dei clienti emerge in diverse conversazioni di esempio.",interpret:"Un tema ricorrente è un’ipotesi iniziale, non la prova di un bisogno dell’intero mercato.",act:"Riunisci le conversazioni originali e verifica il tema con il gruppo di clienti adatto.",measure:"Verifica se la conoscenza validata cambia una proposta, una decisione o un risultato per il cliente."},
  {label:"Contesto di vendita",point:"Momento rilevante",observe:"Un team di gestione clienti di esempio non riesce a vedere facilmente ciò che un cliente ha già discusso.",interpret:"L’opportunità è una conversazione più informata, non semplicemente più contatti.",act:"Fai emergere il contesto rilevante del cliente, nel rispetto delle autorizzazioni, e lascia al team la scelta della risposta.",measure:"Valuta lo sforzo di preparazione, l’utilità per il team e la qualità delle conversazioni che ne derivano."},
  {label:"Nuova proposta",point:"Ipotesi di valore",observe:"Un possibile servizio affronta un problema del cliente, ma la disponibilità ad adottarlo è sconosciuta.",interpret:"Costruire subito l’offerta completa impegnerebbe risorse prima di verificare l’ipotesi centrale.",act:"Crea un piccolo test della proposta con evidenze chiare necessarie per proseguire.",measure:"Esamina l’interesse dimostrato, le barriere all’adozione e la decisione di sviluppare, adattare o fermarsi."}
 ]},
 operate:{name:"Operare meglio",kind:'flow',image:'trade-port',label:"Progetta il lavoro intorno alla decisione.",question:"Cosa deve fluire e cosa richiede giudizio?",inputs:"Conoscenza dei processi · Esempi di lavoro · Responsabilità decisionale",scenarios:[
  {label:"Ridurre gli attriti",point:"Attività ripetute",observe:"Un flusso di esempio trasferisce le stesse informazioni attraverso tre passaggi di consegne.",interpret:"Automatizzare il processo attuale potrebbe conservarne la complessità superflua.",act:"Elimina i passaggi ridondanti, chiarisci le responsabilità e poi testa la più piccola automazione utile.",measure:"Monitora tempi e rilavorazioni insieme all’esperienza delle persone che svolgono il lavoro."},
  {label:"Supportare il giudizio",point:"Momento decisionale",observe:"Una decisione ricorrente di esempio richiede informazioni distribuite su più fonti.",interpret:"L’intervento utile potrebbe essere una sintesi decisionale più chiara, anziché un agente autonomo.",act:"Porta al responsabile decisionale evidenze collegate alle fonti e mantieni un passaggio esplicito di revisione.",measure:"Esamina tempi di preparazione, qualità delle evidenze e coerenza decisionale."}
 ]},
 grow:{name:"Crescere oltre",kind:'route',image:'agritech-aerial',label:"Dai una direzione all’opportunità.",question:"Quale ipotesi di crescita dovresti verificare per prima?",inputs:"Evidenze dai clienti · Contesto di mercato · Ipotesi sulla proposta",scenarios:[
  {label:"Individua il bisogno",point:"Problema del cliente",observe:"Un gruppo di clienti di esempio ricorre a una soluzione di ripiego per un problema ricorrente.",interpret:"La soluzione di ripiego può rivelare valore non soddisfatto, ma dimensione e urgenza del bisogno restano incerte.",act:"Verifica il problema con quel gruppo prima di impegnarti in un nuovo prodotto o servizio.",measure:"Esamina le evidenze del bisogno, le barriere all’adozione e la disponibilità a cambiare."},
  {label:"Scegli un percorso",point:"Percorso di crescita",observe:"Due percorsi di crescita di esempio competono per le stesse risorse.",interpret:"La scelta richiede ipotesi esplicite su adeguatezza, impegno e tempi di apprendimento.",act:"Progetta un test circoscritto per ciascun percorso, poi confronta le evidenze con criteri decisionali condivisi.",measure:"Monitora il costo dell’apprendimento e le evidenze a sostegno della decisione di proseguire, adattare o fermarsi."}
 ]},
 invest:{name:"Investire meglio",kind:'evidence',image:'investment-table',label:"Ogni impegno ha una ragione.",question:"Costruire, acquistare, integrare o aspettare?",inputs:"Esigenza aziendale · Vincoli dei sistemi · Valore nell’intero ciclo di vita",scenarios:[
  {label:"Scegli la risposta",point:"Criteri decisionali",observe:"Un team di esempio vuole un nuovo sistema AI, ma parte delle esigenze potrebbe essere già coperta.",interpret:"La nuova tecnologia è solo una delle possibili risposte al problema aziendale.",act:"Confronta capacità esistenti, una soluzione da acquistare e uno sviluppo su misura usando gli stessi requisiti.",measure:"Valuta adozione, costo totale, manutenibilità ed evidenze di valore, non la novità dello strumento."},
  {label:"Progetta il ritorno",point:"Ipotesi di valore",observe:"Una proposta elenca benefici senza spiegare quando o come verranno misurati.",interpret:"Una promessa non misurata è difficile da gestire e facile da sovrastimare.",act:"Concorda una base di riferimento, un responsabile del valore, momenti di revisione e condizioni esplicite per fermarsi o cambiare rotta.",measure:"Confronta valore realizzato e costi con il caso concordato, includendo ciò che non è migliorato."}
 ]}
};
export function getScenario(key,index=0){const item=experiences[key];return item?.scenarios[index]||item?.scenarios[0];}
