// Editorial demonstrations, not client data, live analysis or model-generated advice.
export const sectors = ['agritech','trade','investing','operations','commercial'];
export const experiences = {
 agritech:{name:"Agroalimentaire et AgriTech",kind:'field',image:'agritech-aerial',label:"L’intelligence sur le terrain.",question:"Où porter l’attention maintenant ?",inputs:"Observations de terrain · Images aériennes · Contexte opérationnel",scenarios:[
  {label:"Ciblage des ressources",point:"Variabilité dans la parcelle",observe:"Dans cet exemple, une zone diffère de la culture environnante.",interpret:"Une image peut soulever une question, mais ne peut pas en établir seule la cause.",act:"Comparez le signal aérien aux observations de terrain avant de modifier un intrant ou une intervention.",measure:"Suivez le problème vérifié, l’action menée et l’utilisation des ressources par rapport à une référence comparable."},
  {label:"Inspection anticipée",point:"Priorité d’inspection",observe:"Un relevé fictif met en évidence une zone qui mérite un examen approfondi.",interpret:"La valeur consiste à orienter un temps d’inspection limité, pas à traiter chaque signal comme un diagnostic.",act:"Donnez à l’équipe de terrain une liste d’inspections priorisées, accompagnée des images sources et des incertitudes.",measure:"Comparez le délai de vérification, les problèmes non détectés et les inspections inutiles."},
  {label:"Visibilité sur l’approvisionnement",point:"Du champ au plan",observe:"Dans cet exemple, les perspectives de production ont changé, mais pas le plan d’approvisionnement.",interpret:"Un signal utile doit parvenir aux personnes qui prennent des engagements en aval.",act:"Reliez une mise à jour vérifiée de la production au processus de planification, avec un responsable de décision identifié.",measure:"Examinez la précision de la planification, les reprises et la rapidité de la réponse convenue."}
 ]},
 trade:{name:"Export et commerce",kind:'route',image:'trade-port',label:"La clarté au-delà des frontières.",question:"Quelle opportunité mérite la prochaine action ?",inputs:"Signaux de marché · Préparation commerciale · Contraintes d’accès",scenarios:[
  {label:"Entrée sur le marché",point:"Signal de marché",observe:"Un marché fictif suscite l’intérêt des clients, mais la manière de le servir n’a pas été testée.",interpret:"La demande n’est qu’une partie de la décision. Livraison, marge et préparation locale doivent encore être étayées.",act:"Préparez une note qui distingue la demande confirmée des hypothèses et des contraintes non résolues.",measure:"Suivez le coût et la rapidité de validation de l’opportunité avant de vous engager dans l’expansion."},
  {label:"Processus commercial",point:"Transmission des documents",observe:"Dans cet exemple, plusieurs équipes saisissent les mêmes informations d’expédition.",interpret:"Les manipulations répétées peuvent brouiller les responsabilités et créer du travail évitable.",act:"Cartographiez les relais et testez une source d’information commune, en conservant la revue spécialisée des décisions de conformité.",measure:"Comparez les délais de traitement, les corrections et les exceptions avant et après un pilote contrôlé."},
  {label:"Priorités commerciales",point:"Accès au client",observe:"Plusieurs demandes à l’export se disputent l’attention de la même équipe.",interpret:"La commande apparemment la plus importante n’est pas forcément la meilleure opportunité.",act:"Comparez préparation, adéquation au client et hypothèses de livraison dans une même note de décision partagée.",measure:"Évaluez l’effort de qualification et la progression selon les critères convenus par l’équipe commerciale."}
 ]},
 investing:{name:"Finance et investissement",kind:'evidence',image:'investment-table',label:"Les preuves avant la conviction.",question:"Qu’est-ce qui changerait votre décision ?",inputs:"Sources · Hypothèses de valeur · Critères de décision",scenarios:[
  {label:"Analyse approfondie",point:"Preuve manquante",observe:"Un dossier d’investissement fictif repose sur une amélioration opérationnelle non vérifiée.",interpret:"Un récit convaincant ne vaut pas un levier de valeur démontré.",act:"Remontez de l’hypothèse aux sources et confiez à l’équipe de due diligence une question à résoudre.",measure:"Suivez les hypothèses importantes qui sont vérifiées, remises en question ou laissées en suspens avant la décision."},
  {label:"Vue du portefeuille",point:"Perspective partagée",observe:"Dans cet exemple, les mises à jour du portefeuille décrivent la performance de différentes façons.",interpret:"La comparaison devient difficile lorsque les définitions, les périodes et les responsabilités diffèrent.",act:"Convenez d’une structure commune des éléments probants et faites ressortir les exceptions sans perdre le contexte de gestion.",measure:"Évaluez l’effort de reporting, la comparabilité et le temps consacré aux questions importantes."},
  {label:"Dossier technologique",point:"Levier de valeur",observe:"La proposition fictive promet une automatisation, mais omet l’adoption et les coûts de fonctionnement.",interpret:"La décision exige une vision du cycle de vie complet, pas une simple promesse d’efficacité.",act:"Construisez un dossier transparent avec les coûts, les dépendances, les hypothèses d’adoption et une condition d’arrêt.",measure:"Comparez la valeur réalisée aux hypothèses initiales et au coût total de possession."}
 ]},
 operations:{name:"Opérations et chaînes d’approvisionnement",kind:'flow',image:'trade-port',label:"Moins de frictions. Plus de fluidité.",question:"Où le travail perd-il son élan ?",inputs:"Événements de processus · Relais entre équipes · Historique des exceptions",scenarios:[
  {label:"Passages de relais",point:"Point d’attente",observe:"Une commande illustrative attend un relais manuel entre deux équipes.",interpret:"Le blocage peut venir d’une responsabilité mal définie plutôt que d’un outil manquant.",act:"Cartographiez la décision et testez un relais plus clair avant d’introduire l’automatisation.",measure:"Comparez les délais, les reprises et le nombre d’exceptions non résolues."},
  {label:"Prévisions",point:"Signal de planification",observe:"Dans cet exemple, la planification utilise une ancienne vision de la demande alors que de nouveaux signaux sont disponibles ailleurs.",interpret:"Une donnée plus récente n’est utile que si elle peut modifier une décision de planification dont la responsabilité est claire.",act:"Intégrez les signaux pertinents à un processus de planification revu et testez-les par rapport à la référence existante.",measure:"Évaluez l’erreur de prévision, l’effort de planification et les conséquences des décisions modifiées."},
  {label:'Exceptions',point:"Jugement humain",observe:"La plupart des commandes fictives suivent un parcours prévisible ; certaines exigent un jugement expérimenté.",interpret:"Traiter tous les cas de la même manière fait perdre du temps ou masque les cas inhabituels.",act:"Séparez le traitement courant d’une file d’exceptions explicite, sous responsabilité humaine.",measure:"Suivez les traitements sans intervention manuelle, ainsi que les taux d’erreur et les exceptions non résolues."}
 ]},
 commercial:{name:"Croissance et développement commercial",kind:'flow',image:'investment-table',label:"Comprendre. Puis agir.",question:"Que vous disent vos clients ?",inputs:"Conversations clients · Signaux commerciaux · Savoir des équipes",scenarios:[
  {label:"Connaissance client",point:"Signal ignoré",observe:"Une préoccupation récurrente des clients apparaît dans plusieurs conversations fictives.",interpret:"Un thème récurrent est une hypothèse de départ, pas la preuve d’un besoin de tout le marché.",act:"Rassemblez les conversations sources et testez le thème auprès du bon groupe de clients.",measure:"Vérifiez si l’enseignement validé modifie une offre, une décision ou un résultat client."},
  {label:"Contexte commercial",point:"Moment pertinent",observe:"Une équipe de compte fictive ne voit pas facilement ce qu’un client a déjà évoqué.",interpret:"L’opportunité est une conversation mieux informée, pas simplement davantage de sollicitations.",act:"Faites ressortir le contexte client pertinent, dans le respect des autorisations, et laissez l’équipe choisir sa réponse.",measure:"Évaluez l’effort de préparation, l’utilité pour l’équipe et la qualité des conversations qui en résultent."},
  {label:"Nouvelle offre",point:"Hypothèse de valeur",observe:"Un service potentiel répond à un problème client, mais la volonté de l’adopter reste inconnue.",interpret:"Construire toute l’offre maintenant engagerait des ressources avant de tester l’hypothèse centrale.",act:"Créez un test limité de l’offre, avec des preuves clairement définies pour poursuivre.",measure:"Examinez l’intérêt démontré, les freins à l’adoption et la décision de développer, d’adapter ou d’arrêter."}
 ]},
 operate:{name:"Mieux opérer",kind:'flow',image:'trade-port',label:"Organisez le travail autour de la décision.",question:"Qu’est-ce qui doit être fluide, et qu’est-ce qui exige du jugement ?",inputs:"Connaissance des processus · Exemples de travail · Responsabilité décisionnelle",scenarios:[
  {label:"Réduire les frictions",point:"Efforts répétés",observe:"Un processus type fait circuler les mêmes informations entre trois relais.",interpret:"Automatiser le processus actuel pourrait en conserver la complexité inutile.",act:"Supprimez les étapes redondantes, clarifiez les responsabilités, puis testez l’automatisation utile la plus simple.",measure:"Suivez les délais et les reprises, ainsi que l’expérience des personnes qui réalisent le travail."},
  {label:"Éclairer le jugement",point:"Moment de décision",observe:"Une décision récurrente fictive nécessite des informations réparties entre plusieurs sources.",interpret:"L’intervention utile peut être une note de décision plus claire plutôt qu’un agent autonome.",act:"Apportez au décideur des preuves reliées aux sources et conservez une étape de revue explicite.",measure:"Examinez le temps de préparation, la qualité des preuves et la cohérence des décisions."}
 ]},
 grow:{name:"Grandir davantage",kind:'route',image:'agritech-aerial',label:"Donnez une direction à l’opportunité.",question:"Quelle hypothèse de croissance tester en premier ?",inputs:"Éléments clients · Contexte de marché · Hypothèses sur l’offre",scenarios:[
  {label:"Identifier le besoin",point:"Problème client",observe:"Un groupe de clients fictif utilise une solution de contournement pour un problème récurrent.",interpret:"Cette solution peut révéler un besoin non satisfait, mais son ampleur et son urgence restent incertaines.",act:"Validez le problème auprès de ce groupe avant d’investir dans un nouveau produit ou service.",measure:"Examinez les preuves du besoin, les freins à l’adoption et la volonté de changer."},
  {label:"Choisir une voie",point:"Trajectoire de croissance",observe:"Deux trajectoires de croissance fictives mobilisent les mêmes ressources.",interpret:"Le choix exige des hypothèses explicites sur l’adéquation, l’effort et le délai d’apprentissage.",act:"Concevez un test limité pour chaque voie, puis comparez les preuves selon des critères de décision communs.",measure:"Suivez le coût de l’apprentissage et les preuves qui justifient de poursuivre, d’adapter ou d’arrêter."}
 ]},
 invest:{name:"Mieux investir",kind:'evidence',image:'investment-table',label:"Chaque engagement doit se justifier.",question:"Construire, acheter, intégrer ou attendre ?",inputs:"Besoin métier · Contraintes des systèmes · Valeur sur le cycle de vie",scenarios:[
  {label:"Choisir la réponse",point:"Critères de décision",observe:"Une équipe fictive souhaite un nouveau système IA, mais une partie de ses besoins est peut-être déjà couverte.",interpret:"Une nouvelle technologie n’est qu’une réponse possible au problème métier.",act:"Comparez les capacités existantes, une solution du marché et un développement sur mesure selon les mêmes exigences.",measure:"Évaluez l’adoption, le coût total, la maintenabilité et les preuves de valeur, pas la nouveauté de l’outil."},
  {label:"Concevoir le retour",point:"Hypothèses de valeur",observe:"Une proposition énumère des bénéfices sans expliquer quand ni comment ils seront mesurés.",interpret:"Une promesse non mesurée est difficile à piloter et facile à exagérer.",act:"Convenez d’une référence, d’un responsable de la valeur, de points de revue et de conditions explicites pour arrêter ou changer de cap.",measure:"Comparez la valeur réalisée et les coûts au dossier convenu, y compris ce qui ne s’est pas amélioré."}
 ]}
};
export function getScenario(key,index=0){const item=experiences[key];return item?.scenarios[index]||item?.scenarios[0];}
